using System;
namespace Freeria
{
	public class Recipe
	{
		public static int maxRequirements = 10;
		public static int maxRecipes = 300;
		public static int numRecipes = 0;
		private static Recipe newRecipe = new Recipe();
		public Item createItem = new Item();
		public Item[] requiredItem = new Item[Recipe.maxRequirements];
		public int[] requiredTile = new int[Recipe.maxRequirements];
		public bool needWater;
		public Recipe()
		{
			for (int i = 0; i < Recipe.maxRequirements; i++)
			{
				this.requiredItem[i] = new Item();
				this.requiredTile[i] = -1;
			}
		}
		public void Create()
		{
			int num = 0;
			while (num < Recipe.maxRequirements && this.requiredItem[num].type != 0)
			{
				int num2 = this.requiredItem[num].stack;
				for (int i = 0; i < 44; i++)
				{
					if (Main.player[Main.myPlayer].inventory[i].IsTheSameAs(this.requiredItem[num]))
					{
						if (Main.player[Main.myPlayer].inventory[i].stack > num2)
						{
							Main.player[Main.myPlayer].inventory[i].stack -= num2;
							num2 = 0;
						}
						else
						{
							num2 -= Main.player[Main.myPlayer].inventory[i].stack;
							Main.player[Main.myPlayer].inventory[i] = new Item();
						}
					}
					if (num2 <= 0)
					{
						break;
					}
				}
				num++;
			}
			Recipe.FindRecipes();
		}
		public static void FindRecipes()
		{
			int num = Main.availableRecipe[Main.focusRecipe];
			float num2 = Main.availableRecipeY[Main.focusRecipe];
			for (int i = 0; i < Recipe.maxRecipes; i++)
			{
				Main.availableRecipe[i] = 0;
			}
			Main.numAvailableRecipes = 0;
			int num3 = 0;
			while (num3 < Recipe.maxRecipes && Main.recipe[num3].createItem.type != 0)
			{
				bool flag = true;
				bool flag2 = false;
				if (Main.guideItem.type > 0 && Main.guideItem.stack > 0 && Main.guideItem.name != "")
				{
					flag2 = true;
				}
				if (flag2)
				{
					for (int j = 0; j < Recipe.maxRequirements; j++)
					{
						if (Main.recipe[num3].requiredItem[j].type == 0)
						{
							break;
						}
						if (Main.guideItem.IsTheSameAs(Main.recipe[num3].requiredItem[j]))
						{
							Main.availableRecipe[Main.numAvailableRecipes] = num3;
							Main.numAvailableRecipes++;
							break;
						}
					}
				}
				else
				{
					int num4 = 0;
					while (num4 < Recipe.maxRequirements && Main.recipe[num3].requiredItem[num4].type != 0)
					{
						int num5 = Main.recipe[num3].requiredItem[num4].stack;
						for (int k = 0; k < 44; k++)
						{
							if (Main.player[Main.myPlayer].inventory[k].IsTheSameAs(Main.recipe[num3].requiredItem[num4]))
							{
								num5 -= Main.player[Main.myPlayer].inventory[k].stack;
							}
							if (num5 <= 0)
							{
								break;
							}
						}
						if (num5 > 0)
						{
							flag = false;
							break;
						}
						num4++;
					}
					if (flag)
					{
						bool flag3 = true;
						int num6 = 0;
						while (num6 < Recipe.maxRequirements && Main.recipe[num3].requiredTile[num6] != -1)
						{
							if (!Main.player[Main.myPlayer].adjTile[Main.recipe[num3].requiredTile[num6]])
							{
								flag3 = false;
								break;
							}
							num6++;
						}
						if (flag3 && (!Main.recipe[num3].needWater || Main.recipe[num3].needWater == Main.player[Main.myPlayer].adjWater))
						{
							Main.availableRecipe[Main.numAvailableRecipes] = num3;
							Main.numAvailableRecipes++;
						}
					}
				}
				num3++;
			}
			for (int l = 0; l < Main.numAvailableRecipes; l++)
			{
				if (num == Main.availableRecipe[l])
				{
					Main.focusRecipe = l;
					break;
				}
			}
			if (Main.focusRecipe >= Main.numAvailableRecipes)
			{
				Main.focusRecipe = Main.numAvailableRecipes - 1;
			}
			if (Main.focusRecipe < 0)
			{
				Main.focusRecipe = 0;
			}
			float num7 = Main.availableRecipeY[Main.focusRecipe] - num2;
			for (int m = 0; m < Recipe.maxRecipes; m++)
			{
				Main.availableRecipeY[m] -= num7;
			}
		}
		public static void SetupRecipes()
		{
			Recipe.newRecipe.createItem.SetDefaults("Mug");
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Glass");
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bowl of Soup");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Bowl");
			Recipe.newRecipe.requiredItem[1].SetDefaults("Mushroom");
			Recipe.newRecipe.requiredItem[2].SetDefaults("Goldfish");
			Recipe.newRecipe.requiredTile[0] = 96;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bottle");
			Recipe.newRecipe.createItem.stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Glass");
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bottled Water");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Bottle");
			Recipe.newRecipe.needWater = true;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Ale");
			Recipe.newRecipe.requiredItem[0].SetDefaults(351, false);
			Recipe.newRecipe.requiredTile[0] = 94;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(28, false);
			Recipe.newRecipe.createItem.stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults(5, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23, false);
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults(31, false);
			Recipe.newRecipe.requiredItem[2].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Healing Potion");
			Recipe.newRecipe.requiredItem[0].SetDefaults(28, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults(183, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(110, false);
			Recipe.newRecipe.createItem.stack = 2;
			Recipe.newRecipe.requiredItem[0].SetDefaults(75, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23, false);
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults(31, false);
			Recipe.newRecipe.requiredItem[2].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Mana Potion");
			Recipe.newRecipe.requiredItem[0].SetDefaults(110, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults(183, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(226, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(28, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(110, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(227, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Healing Potion");
			Recipe.newRecipe.requiredItem[1].SetDefaults("Mana Potion");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(288, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(318, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(317, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults("Obsidian");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(289, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Mushroom");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(290, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Cactus");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(291, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(317, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Coral");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(292, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Iron Ore");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(293, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(314, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults("Fallen Star");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(294, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(314, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(316, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults("Fallen Star");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(295, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults("Feather");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(296, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(314, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults("Gold Ore");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(297, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(314, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(298, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Glowing Mushroom");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(299, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(315, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(300, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(316, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Rotten Chunk");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(301, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(316, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Cactus");
			Recipe.newRecipe.requiredItem[3].SetDefaults("Worm Teeth");
			Recipe.newRecipe.requiredItem[4].SetDefaults("Stinger");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(302, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(317, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(319, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(303, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults("Lens");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(304, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(313, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults(319, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(305, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(126, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(318, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(316, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults(315, false);
			Recipe.newRecipe.requiredItem[4].SetDefaults("Feather");
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(255, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(31, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(195, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(67, false);
			Recipe.newRecipe.createItem.stack = 5;
			Recipe.newRecipe.requiredItem[0].SetDefaults(60, false);
			Recipe.newRecipe.requiredTile[0] = 13;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(287, false);
			Recipe.newRecipe.createItem.stack = 20;
			Recipe.newRecipe.requiredItem[0].SetDefaults(279, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(67, false);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(8, false);
			Recipe.newRecipe.createItem.stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(23, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Chinese Lantern");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 5;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Torch");
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Tiki Torch");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Torch");
			Recipe.newRecipe.requiredItem[1].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Lamp Post");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Glass");
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults("Torch");
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Skull Lantern");
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Bone");
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Torch");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(235, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(166, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23, false);
			Recipe.newRecipe.requiredItem[1].stack = 5;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(286, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(282, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(23, false);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Glass");
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(169, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Clay Pot");
			Recipe.newRecipe.requiredItem[0].SetDefaults(133, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Pink Vase");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Clay Block");
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bowl");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Clay Block");
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gray Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gray Brick Wall");
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gray Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Red Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(133, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Red Brick Wall");
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Red Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Copper Ore");
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Brick Wall");
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Copper Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Brick Wall");
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silver Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Silver Ore");
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Brick Wall");
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gold Brick");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Gold Ore");
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Hellstone Brick");
			Recipe.newRecipe.requiredItem[0].SetDefaults(174, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(3, false);
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(192, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(173, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(330, false);
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(192, false);
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(30, false);
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(2, false);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(26, false);
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(93, false);
			Recipe.newRecipe.createItem.stack = 4;
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(94, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(25, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(34, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Sign");
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(48, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredItem[1].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(32, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(36, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bookcase");
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Book");
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Barrel");
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Grandfather Clock");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gold Bar");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Glass");
			Recipe.newRecipe.requiredItem[1].stack = 6;
			Recipe.newRecipe.requiredItem[2].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[2].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Keg");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 14;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Piano");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Bone");
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[1].stack = 15;
			Recipe.newRecipe.requiredItem[2].SetDefaults("Book");
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Loom");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Dresser");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 16;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bench");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Sawmill");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Iron Bar");
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredItem[2].SetDefaults("Iron Chain");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(24, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(196, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(40, false);
			Recipe.newRecipe.createItem.stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(3, false);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(39, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bed");
			Recipe.newRecipe.requiredItem[0].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[1].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 106;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(361, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(362, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[1].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].SetDefaults(150, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Red Banner");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Green Banner");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Blue Banner");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Yellow Banner");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(247, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(255, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(248, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(255, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(249, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(255, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(240, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(254, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(241, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(254, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(262, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults(178, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 86;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(259, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(68, false);
			Recipe.newRecipe.requiredItem[0].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(252, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(259, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(253, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(259, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(250, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(261, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Bottled Water");
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Flaming Arrow");
			Recipe.newRecipe.createItem.stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(40, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8, false);
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(33, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(3, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(8, false);
			Recipe.newRecipe.requiredItem[2].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Statue");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Stone Block");
			Recipe.newRecipe.requiredItem[0].stack = 100;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(12, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Shortsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Copper Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(11, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(35, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(205, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Trash Can");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Bathtub");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 14;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Toilet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Cooking Pot");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Iron Bar");
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Wood");
			Recipe.newRecipe.requiredItem[1].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(1, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(10, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(7, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(4, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(6, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Iron Chain");
			Recipe.newRecipe.requiredItem[0].SetDefaults(22, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(14, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Shortsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Silver Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(13, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Axe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 9;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Hammer");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(9, false);
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Broadsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Shortsword");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Bow");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 7;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Chainmail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Watch");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Crown");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Ruby");
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Gold Chandelier");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(8, false);
			Recipe.newRecipe.requiredItem[1].stack = 4;
			Recipe.newRecipe.requiredItem[2].SetDefaults(85, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Throne");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silk");
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Gold Bar");
			Recipe.newRecipe.requiredItem[1].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Candle");
			Recipe.newRecipe.requiredItem[0].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(8, false);
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Candelabra");
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Gold Bar");
			Recipe.newRecipe.requiredItem[0].stack = 5;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Torch");
			Recipe.newRecipe.requiredItem[1].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(56, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(44, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 8;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Unholy Arrow");
			Recipe.newRecipe.createItem.stack = 3;
			Recipe.newRecipe.requiredItem[0].SetDefaults(40, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults(69, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(45, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(46, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Scalemail");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86, false);
			Recipe.newRecipe.requiredItem[1].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Shadow Greaves");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86, false);
			Recipe.newRecipe.requiredItem[1].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Nightmare Pickaxe");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 12;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86, false);
			Recipe.newRecipe.requiredItem[1].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("The Breaker");
			Recipe.newRecipe.requiredItem[0].SetDefaults(57, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(86, false);
			Recipe.newRecipe.requiredItem[1].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Grappling Hook");
			Recipe.newRecipe.requiredItem[0].SetDefaults(85, false);
			Recipe.newRecipe.requiredItem[0].stack = 3;
			Recipe.newRecipe.requiredItem[1].SetDefaults(118, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(116, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(198, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(177, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(199, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(178, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(200, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(179, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(201, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(181, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(202, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(182, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(203, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults(180, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(204, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(127, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(95, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[1].stack = 30;
			Recipe.newRecipe.requiredItem[2].SetDefaults(75, false);
			Recipe.newRecipe.requiredItem[2].stack = 10;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(197, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(98, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[1].stack = 20;
			Recipe.newRecipe.requiredItem[2].SetDefaults(75, false);
			Recipe.newRecipe.requiredItem[2].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Helmet");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Suit");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Leggings");
			Recipe.newRecipe.requiredItem[0].SetDefaults(117, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Meteor Shot");
			Recipe.newRecipe.createItem.stack = 25;
			Recipe.newRecipe.requiredItem[0].SetDefaults("Musket Ball");
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredItem[1].SetDefaults(117, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(151, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150, false);
			Recipe.newRecipe.requiredItem[1].stack = 40;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(152, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150, false);
			Recipe.newRecipe.requiredItem[1].stack = 50;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(153, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(154, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults(150, false);
			Recipe.newRecipe.requiredItem[1].stack = 45;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(190, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults("Silver Broadsword");
			Recipe.newRecipe.requiredItem[1].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[1].stack = 20;
			Recipe.newRecipe.requiredItem[2].SetDefaults(209, false);
			Recipe.newRecipe.requiredItem[2].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(191, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults(209, false);
			Recipe.newRecipe.requiredItem[1].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(185, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(84, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[1].stack = 15;
			Recipe.newRecipe.requiredItem[2].SetDefaults(210, false);
			Recipe.newRecipe.requiredItem[2].stack = 3;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(228, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(91, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(179, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredItem[2].SetDefaults(177, false);
			Recipe.newRecipe.requiredItem[2].stack = 1;
			Recipe.newRecipe.requiredItem[3].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[3].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(229, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(82, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(178, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredItem[2].SetDefaults(182, false);
			Recipe.newRecipe.requiredItem[2].stack = 1;
			Recipe.newRecipe.requiredItem[3].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[3].stack = 20;
			Recipe.newRecipe.requiredItem[4].SetDefaults(209, false);
			Recipe.newRecipe.requiredItem[4].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(230, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(78, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(181, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredItem[2].SetDefaults(180, false);
			Recipe.newRecipe.requiredItem[2].stack = 1;
			Recipe.newRecipe.requiredItem[3].SetDefaults(331, false);
			Recipe.newRecipe.requiredItem[3].stack = 20;
			Recipe.newRecipe.requiredItem[4].SetDefaults(210, false);
			Recipe.newRecipe.requiredItem[4].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(174, false);
			Recipe.newRecipe.requiredItem[0].stack = 4;
			Recipe.newRecipe.requiredItem[1].SetDefaults(173, false);
			Recipe.newRecipe.requiredItem[1].stack = 1;
			Recipe.newRecipe.requiredTile[0] = 77;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(119, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 15;
			Recipe.newRecipe.requiredItem[1].SetDefaults(55, false);
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(120, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 25;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(121, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(122, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(217, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(219, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredItem[1].SetDefaults("Handgun");
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(231, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(92, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[1].stack = 30;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(232, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(83, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[1].stack = 40;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(233, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(79, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(175, false);
			Recipe.newRecipe.requiredItem[1].stack = 35;
			Recipe.newRecipe.requiredTile[0] = 16;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(273, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(46, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(155, false);
			Recipe.newRecipe.requiredItem[2].SetDefaults(190, false);
			Recipe.newRecipe.requiredItem[3].SetDefaults(121, false);
			Recipe.newRecipe.requiredTile[0] = 26;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Depth Meter");
			Recipe.newRecipe.requiredItem[0].SetDefaults(20, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.newRecipe.requiredItem[1].SetDefaults(21, false);
			Recipe.newRecipe.requiredItem[1].stack = 8;
			Recipe.newRecipe.requiredItem[2].SetDefaults(19, false);
			Recipe.newRecipe.requiredItem[2].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 14;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(193, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(173, false);
			Recipe.newRecipe.requiredItem[0].stack = 20;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Goggles");
			Recipe.newRecipe.requiredItem[0].SetDefaults(38, false);
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(266, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(324, false);
			Recipe.newRecipe.requiredItem[1].SetDefaults(323, false);
			Recipe.newRecipe.requiredItem[1].stack = 10;
			Recipe.newRecipe.requiredItem[2].SetDefaults(180, false);
			Recipe.newRecipe.requiredItem[2].stack = 5;
			Recipe.newRecipe.requiredTile[0] = 17;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Sunglasses");
			Recipe.newRecipe.requiredItem[0].SetDefaults("Black Lens");
			Recipe.newRecipe.requiredItem[0].stack = 2;
			Recipe.newRecipe.requiredTile[0] = 18;
			Recipe.newRecipe.requiredTile[1] = 15;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults("Mana Crystal");
			Recipe.newRecipe.requiredItem[0].SetDefaults(75, false);
			Recipe.newRecipe.requiredItem[0].stack = 10;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(43, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(38, false);
			Recipe.newRecipe.requiredItem[0].stack = 6;
			Recipe.newRecipe.requiredTile[0] = 26;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(70, false);
			Recipe.newRecipe.requiredItem[0].SetDefaults(67, false);
			Recipe.newRecipe.requiredItem[0].stack = 30;
			Recipe.newRecipe.requiredItem[1].SetDefaults(68, false);
			Recipe.newRecipe.requiredItem[1].stack = 15;
			Recipe.newRecipe.requiredTile[0] = 26;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(71, false);
			Recipe.newRecipe.createItem.stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(72, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(72, false);
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(71, false);
			Recipe.newRecipe.requiredItem[0].stack = 100;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(72, false);
			Recipe.newRecipe.createItem.stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(73, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(73, false);
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(72, false);
			Recipe.newRecipe.requiredItem[0].stack = 100;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(73, false);
			Recipe.newRecipe.createItem.stack = 100;
			Recipe.newRecipe.requiredItem[0].SetDefaults(74, false);
			Recipe.newRecipe.requiredItem[0].stack = 1;
			Recipe.addRecipe();
			Recipe.newRecipe.createItem.SetDefaults(74, false);
			Recipe.newRecipe.createItem.stack = 1;
			Recipe.newRecipe.requiredItem[0].SetDefaults(73, false);
			Recipe.newRecipe.requiredItem[0].stack = 100;
			Recipe.addRecipe();
			for (int i = 0; i < Recipe.numRecipes; i++)
			{
				int num = 0;
				while (Main.recipe[i].requiredItem[num].type > 0)
				{
					Main.recipe[i].requiredItem[num].checkMat();
					num++;
				}
				Main.recipe[i].createItem.checkMat();
			}
		}
		private static void addRecipe()
		{
			Main.recipe[Recipe.numRecipes] = Recipe.newRecipe;
			Recipe.newRecipe = new Recipe();
			Recipe.numRecipes++;
		}
	}
}
